import React from 'react';
import { Link } from 'react-router-dom';
import { DocumentIcon, ArrowLeftIcon } from '@heroicons/react/24/outline';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-dark-primary py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <Link 
          to="/" 
          className="inline-flex items-center text-dark-neon-blue hover:text-dark-neon-green transition-colors mb-8"
        >
          <ArrowLeftIcon className="h-5 w-5 mr-2" />
          Back to Home
        </Link>

        <div className="flex items-center mb-8">
          <DocumentIcon className="h-12 w-12 text-dark-neon-purple mr-4" />
          <h1 className="text-4xl font-bold neon-text">Terms of Service</h1>
        </div>

        <div className="bg-dark-secondary rounded-xl p-8 border border-dark-muted space-y-6 text-gray-300">
          <p className="text-sm text-gray-400">Last Updated: November 13, 2025</p>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Exam AI Malawi ("the Service"), you accept and agree to be bound by these Terms of 
              Service. If you do not agree to these terms, please do not use our Service. These terms apply to all users, 
              including students, educators, and visitors.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
            <p>
              Exam AI Malawi is an AI-powered educational platform designed to help Malawian students prepare for exams. 
              The Service provides:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4 mt-3">
              <li>AI-generated practice questions and exams</li>
              <li>Personalized study assistance</li>
              <li>Progress tracking and analytics</li>
              <li>Subject-specific learning materials</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. User Accounts and Registration</h2>
            
            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3">Account Creation</h3>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You must provide accurate and complete information when creating an account</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              <li>You must be at least 13 years old to create an account (with parental consent if under 18)</li>
              <li>One person or entity may not maintain multiple accounts</li>
            </ul>

            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3 mt-4">Account Security</h3>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You are responsible for all activities under your account</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>We are not liable for losses caused by unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Acceptable Use Policy</h2>
            <p className="mb-3">You agree NOT to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Use the Service for any illegal purpose or in violation of any laws</li>
              <li>Share, sell, or redistribute content generated by the platform</li>
              <li>Attempt to reverse engineer, hack, or compromise the Service</li>
              <li>Use automated systems (bots) to access the Service</li>
              <li>Harass, abuse, or harm other users</li>
              <li>Upload malicious code or viruses</li>
              <li>Violate intellectual property rights</li>
              <li>Use the Service to cheat on actual exams or assessments</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Intellectual Property Rights</h2>
            
            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3">Our Rights</h3>
            <p>
              All content, features, and functionality of the Service, including but not limited to text, graphics, logos, 
              AI algorithms, and software, are owned by Fatty AI-Ed-Tech and are protected by copyright, trademark, and 
              other intellectual property laws.
            </p>

            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3 mt-4">Your Rights</h3>
            <p>
              You retain ownership of any original content you create. However, by using the Service, you grant us a 
              license to use your data to improve our AI models and provide better service (anonymized and aggregated).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Subscription and Payment</h2>
            
            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3">Free and Premium Plans</h3>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Free Plan:</strong> Limited questions and exams per day</li>
              <li><strong>Premium Plan:</strong> Unlimited access to all features</li>
            </ul>

            <h3 className="text-xl font-semibold text-dark-neon-blue mb-3 mt-4">Payment Terms</h3>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Premium subscriptions are billed monthly in advance</li>
              <li>All fees are in Malawian Kwacha (MWK)</li>
              <li>Payment is non-refundable except as required by law</li>
              <li>We reserve the right to change pricing with 30 days notice</li>
              <li>Failure to pay may result in account suspension</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Educational Disclaimer</h2>
            <p>
              Exam AI Malawi is a study aid and should be used as a supplement to, not a replacement for, traditional 
              education. We do not guarantee exam success or specific learning outcomes. The AI-generated content is for 
              practice purposes only and may contain errors. Always verify information with official educational resources.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Fatty AI-Ed-Tech and Exam AI Malawi shall not be liable for any 
              indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of 
              profits, data, or academic opportunities, arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Service Availability</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>We strive for 99% uptime but do not guarantee uninterrupted service</li>
              <li>The Service may be temporarily unavailable for maintenance</li>
              <li>We reserve the right to modify or discontinue features</li>
              <li>We may suspend or terminate your account for violations of these terms</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. Termination</h2>
            <p>
              You may terminate your account at any time by contacting us. We may terminate or suspend your account 
              immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other 
              users, us, or third parties, or for any other reason.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Malawi, without regard to 
              its conflict of law provisions. Any disputes arising from these Terms shall be resolved in the courts of Malawi.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of any material changes via 
              email or through the Service. Your continued use after such modifications constitutes acceptance of the 
              updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">13. Contact Information</h2>
            <p className="mb-3">For questions about these Terms, please contact us:</p>
            <div className="bg-dark-accent p-4 rounded-lg">
              <p><strong className="text-dark-neon-purple">Email:</strong> ylikagwa@gmail.com</p>
              <p><strong className="text-dark-neon-purple">Phone/WhatsApp:</strong> +265 880 646 248</p>
              <p><strong className="text-dark-neon-purple">Organization:</strong> Fatty AI-Ed-Tech</p>
            </div>
          </section>

          <section className="border-t border-dark-muted pt-6 mt-8">
            <p className="text-sm text-gray-400">
              By using Exam AI Malawi, you acknowledge that you have read, understood, and agree to be bound by these 
              Terms of Service.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
